package util

const val defaultErrorMessage = "Something Went Wrong!"
const val actionsText = "Actions"
const val idText = "ID"
const val pharmIdText = "Pharm ID"
const val compIdText = "Company ID"
const val inventoryText = "Inventory"
const val priceText = "Price"
const val expirationDateText = "Expiration Date"
const val medNameText = "Med Name"
const val nameText = "Name"
const val needPrcText = "Need Prescription"
const val usageText = "Usage"
const val sideEffectsText = "Side Effects"
const val categoryIdText = "Category ID"
const val descriptionText = "Description"
const val countryText = "Country"
const val emailText = "Email"
const val addressText = "adress"